### ISSUE TITLE
Add link from HTML to corresponding YAML.

### ISSUE THREAD

**Issue by philwong-awtc** [asyncapi/playground#1]
Frustrating trying to find the right place in YAML to make edits. Frustration is compounded because it's hard to search for the right place in yaml. Compounded further because the HTML is sorted alphabetically, so you can't even correlate position in the yaml.

**Comment by fmvilas** [comment]
I hear ya. Maybe we should not be sorting it as a starting point. Regarding having links from YAML to HTML, I think it's a cool feature but also a non-trivial one. I'd be very happy if you could take the lead on both. What do you think?

**Comment by philwong-awtc** [comment]
My heart is willing, but my schedule and brain say otherwise. It’s been a while since I have coded at all and I’m afraid I lost my chops. The chances of me developing this is slim to none. With that said, if I find some free time in the future and I desire to make a programming comeback, I’ll take this ticket if it’s still unclaimed.

BTW, not sorting will be a huge step in the right direction.

Thanks,
Philip
