### ISSUE TITLE
Download documentation as zip file from playground page does not work

### ISSUE THREAD

**Issue by lukaszkowalik** [asyncapi/playground#105]
#### Describe the bug
I observed download action available in playground does no work. 

#### How to Reproduce
I have been using AsyncAPI Playground both from both official page:
- https://playground.asyncapi.io/
- and locally as docker (that I prepared based on https://github.com/asyncapi/playground instruction)
- taken from master: https://github.com/asyncapi/playground/commit/b8a94757562ad130903c2cbe75c37f7dab6db205
- I checked on different browsers, e.g. on Firefox window showed up and download takes forever: "Unknown time left" to download

#### Expected behavior
- it work some time ago and result was that proper zip file was generated

**Comment by derberg** [comment]
@lukaszkowalik it would help us a lot if you narrow down to a specific version when it stopped working 🙏🏼 it would definitely speed up providing the fix

**Comment by AceTheCreator** [comment]
> @lukaszkowalik it would help us a lot if you narrow down to a specific version when it stopped working 🙏🏼 it would definitely speed up providing the fix

@derberg  Please kindly review the PR above.

**Comment by derberg** [comment]
@AceTheCreator lgtm, thanks!

**Comment by lukaszkowalik** [comment]
@AceTheCreator, I double checked your commit. I downloaded it and tested manually. It works. Thank you.
