### ISSUE TITLE
Add query parameter to collapse editor

### ISSUE THREAD

**Issue by MartinMuzatko** [asyncapi/playground#138]
#### Reason/Context
I would like to ber able to quickly share the documentation without having the other one see the source yml file, which is not relevant for the documentation to view.

#### Description
This can be changed here:

https://github.com/asyncapi/playground/blob/master/src/server/views/app.handlebars#L174-L177

We could add the class `left-pane--collapsed` to the element with the class `left-pane`
For the query parameter I propose `collapsed` which can be set to true or false. Or we check by presence of the property.

**Comment by magicmatatjahu** [comment]
@MartinMuzatko Hi! Great idea! To clarify: the collapse button to see the source of spec should be also visible if someone pass as query parameter the `collapsed`, yes? For me it should, but maybe you have a different view of it.

**Comment by MartinMuzatko** [comment]
I can still be visible, I have no problem with that :).
If you want more fine grained control, we could add more options.
I usually add query parameters to hide certain parts of navigational elements if others want to embed or share my app.
Of course you can keep any branding that makes it apparant that it belongs to AsyncAPI.

If it were me, I would also provide an option to hide the second header line (HTML, Markdown and download button). Or even better: preselect what generated documentation should be visible on view (HTML or markdown)

But for now: I'm already satisfied with the `collapsed` option. Thank you for the quick response!

**Comment by magicmatatjahu** [comment]
I suggest two query parameters:
- `collapseEditor` which will collapse the editor. Allowed values: empty or `true`
- `template` which will open the given template. Allowed values: `markdown` and `html`

So query like `?collapseEditor&template=markdown` will collapse the editor and open the render the markdown template. By default editor will be expanded and rendered will be html.

What do you think @MartinMuzatko ?

**Comment by MartinMuzatko** [comment]
Looks good, I like it! I added my two cents to the PR.

**Comment by magicmatatjahu** [comment]
@MartinMuzatko It works! Check out an example https://playground.asyncapi.io/?url=https://raw.githubusercontent.com/asyncapi/spec/1.2.0/test/docs/slack-rtm.yml&readOnly :)
