### ISSUE TITLE
Markdown does not display

### ISSUE THREAD

**Issue by mschechter-bellese** [asyncapi/playground#170]
#### Describe the bug
Instead of the Markdown rendering, the following message is displayed:
```
We found the following errors in your AsyncAPI document:
ENOSPC: no space left on device, write
```

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

1. Navigate to `https://playground.asyncapi.io/?load=https://raw.githubusercontent.com/asyncapi/asyncapi/v2.1.0/examples/simple.yml` (this also happens with the 2.0.0 example)
2. Click `Markdown` in the right-hand pane to switch the rendering type
3. The above error will be displayed

- Screenshot: <img width="1758" alt="image" src="https://user-images.githubusercontent.com/61873300/132867820-bda15d4d-b278-497a-b8ac-938a11e9b18c.png">

#### Expected behavior
The API contract should be rendered as Markdown

**Comment by derberg** [comment]
@mschechter-bellese thanks for reporting it!
@fmvilas redeploy? I guess it is because of logs, we do not need the history

**Comment by fmvilas** [comment]
Yeah, we should get rid of these lines: https://github.com/asyncapi/playground/blob/master/src/server/index.js#L23

**Comment by mschechter-bellese** [comment]
@derberg / @fmvilas,

Looks great! Thanks for the quick response!

**Comment by derberg** [comment]
@fmvilas maybe not get rid but just hide them behind some env variable like `ENABLE_LOGS` and deploy our instance without it but leave others to use it if they want

**Comment by fmvilas** [comment]
Yeah, that would be better indeed.

**Comment by derberg** [comment]
@fmvilas you plan to work on it? easy to do, you could create a separate issue labeled as `good first issue` and we could close this one

**Comment by mschechter-bellese** [comment]
> Done: #172
> 
> I think we can close this one now, right?

Works for me

**Comment by fmvilas** [comment]
Thanks for the heads up, @mschechter-bellese.
