### ISSUE TITLE
yml file does not render/generate anymore.

### ISSUE THREAD

**Issue by MartinMuzatko** [asyncapi/playground#171]
#### Describe the bug
A week ago, our documentation still worked on asyncapi playground. Now I get a blank document and no error for the provided yml file

#### How to Reproduce
See this link: 
https://playground.asyncapi.io/?load=https://app-store-api.service.sicon.eco/uploads/smqtt-public-asyncapi.yml

- Spec: https://app-store-api.service.sicon.eco/uploads/smqtt-public-asyncapi.yml

#### Expected behavior
I should at least get an error, the response from the generate rest api call (https://playground.asyncapi.io/html/generate) only says "If you are the application owner check the logs for more information"

![image](https://user-images.githubusercontent.com/2950505/133060260-508b4fac-d680-4aea-b106-55af4527bb83.png)

**Comment by derberg** [comment]
@MartinMuzatko sorry, we had some issues with playground that our monitoring could not spot. Fixed now

**Comment by derberg** [comment]
@MartinMuzatko just curious, do you plan to render your docs [here](https://docs.exa.sicon.io/developer/mqtt-api-documentation.html) in the future?

**Comment by MartinMuzatko** [comment]
Hi @derberg. We have settled/agreed on having an extra subdomain that provides the API documentation for now ( https://apidocs.service.sicon.eco/ ) ( [see code here](https://gist.github.com/MartinMuzatko/ada6c2ff650acf2cf3eaf024cc597273) ), which is easier for us to maintain and scrape (for our offline documentation), as we migrate from markdown generated docs to Confluence generated docs ( https://sicon-os-help-center.scrollhelp.site/doc/OS-Rest-API.559317647.html )
In the future we will look into versioning our asyncapi documentation. Then it will be likely easier to provide an experience similar to the playground, just with a version dropdown outside the iframe to pick the `?load=` url.

**Comment by derberg** [comment]
@MartinMuzatko thanks for all the details. We always need to know about any publicly available AsyncAPI files because we want community to see it. I will make sure  your company is listed here https://apitracker.io/specifications/asyncapi

As a side note, consider submitting a presentation proposal for our upcoming conference -> https://conference.asyncapi.com/ I always encourage existing end users that use AsyncAPI in production to share their stories with others.
