### ISSUE TITLE
Add ENABLE_DEBUG flag to turn on logging

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/playground#172]
#### Reason/Context
Currently, we're console logging every AsyncAPI document that's received. This is causing memory issues in our production machines. The code is here: https://github.com/asyncapi/playground/blob/master/src/server/index.js#L23

#### Description
We should put this `console.log` under an optional flag like an `ENABLE_DEBUG` environment variable. This way we can control when we want to log things and when we don't want to.

#### Related issues

https://github.com/asyncapi/playground/issues/170

**Comment by derberg** [comment]
please also add `dev` script to `package.json` where `ENABLE_DEBUG=true` is passed to start the server for easier development

**Comment by derberg** [comment]
closing as it is all about `studio` now and `playground` will be soon archived, no sense for anyone to contribute to the project

**Comment by derberg** [comment]
closing as it is all about `studio` now and `playground` will be soon archived, no need for anyone to contribute to the project
