### ISSUE TITLE
Recursive Error with Self-Referenced References

### ISSUE THREAD

**Issue by jdgiotta** [asyncapi/playground#20]
#### Describe the bug
If you define a component that has a property of the given component a recursive error occurs.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

![image](https://user-images.githubusercontent.com/1541999/85064029-f900ea00-b178-11ea-9ab8-e19cb013b9f6.png)
 Create a example component with 2 fields. The first is an irrelevant string type named "name". The second is a field that references the same component.

Example:

```
Category:
      type: object
      properties:
        "name":
          type: string
          example: "AFB"
        "subcategory":
          $ref: '#/components/schemas/Category'
```

#### Expected behavior
Probably should allow this behavior once or twice then stop.

**Comment by derberg** [comment]
@jdgiotta hi thanks for reporting it. We are aware of the problem, just figuring out what is the best solution for that. Feel invited to join discussion https://github.com/asyncapi/parser-js/issues/83

also, I recommend you don't use the playground as we did not update it with few releases and do not plan to update further. Better switch to https://hub.asyncapi.io/. And yes, I know, we should make this information much more visible, and yes, we are working on that 😄 new website is on its way, max 2 weeks and it will be released

- pr https://github.com/asyncapi/website/pull/108
- preview https://deploy-preview-108--asyncapi-website.netlify.app/

**Comment by jdgiotta** [comment]
Excellent. Thank you for the new tool, by the way.

**Comment by derberg** [comment]
Playground updated with the fix and support for circular refs
