### ISSUE TITLE
Open asyncapi based on URL parameter

### ISSUE THREAD

**Issue by galvo** [asyncapi/playground#26]
#### Reason/Context
Please try answering few of those questions

- Why we need this improvement?
It is useful to be able to call the URL directly and pass in the URL of the async file rather than have to use text box and "Import document" button. For instance if you could use URL https://playground.asyncapi.io/?url=https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/streetlights.yml to render this async api. Swagger UI and Editor have similar mechanisms.

- How will this change help?
It will allow you to pass around a URL for an async api rather than have to manually specify it in UI.

- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
No
- How could it be implemented/designed?

**Comment by derberg** [comment]
to summarize what needs to be done:
- here https://github.com/asyncapi/playground/blob/master/src/server/views/app.handlebars#L100-L112 we should keep support for `load` param and add support for `url` param that is much more intuitive
- update readme with information how someone can pass link to the playground in the way that it already points to some specification stored remotely

**Comment by Orodan** [comment]
Hey, I'll give it a try :)

**Comment by derberg** [comment]
@Orodan we talked about this issue during our stream yesterday, so you might want to check it out https://youtu.be/wqp0uoLbChg?t=2391
