### ISSUE TITLE
Docker expossed port is not reachable

### ISSUE THREAD

**Issue by armhzjz** [asyncapi/playground#34]
#### Describe the bug
After running a container (as indicated in the README.md file), the expossed port (i.e. 83) is not reachable.

#### How to Reproduce
Build an image according to the instructions (maybe with --network=host passed as argument to the docker build command) and run a container of the newly created docker images following the command indicated in the documentation (i.e. README.md).
After that try to access `localhost:5000` --> nothing happens.

#### Expected behavior
I expected to see the playground page where I could create an AsyncAPI definition and get its documentation as HTML.

###Additional note:
Could it be that this issue is produced by the application serving to a specific ip address (i.e. to 127.0.0.1 instead of 0.0.0.0) or any other misconfiguration?
(Unfortunatelly I am not familiar with node.js/java/nginx).

**Comment by fmvilas** [comment]
Hey Armando. I just tried to reproduce it and it's working fine for me. I'm using Mac and I know it works on Linux because it's working on the server. May it be something else in your machine?

**Comment by armhzjz** [comment]
Hi Fran. I will close this issue. Just found out couple of minutes ago that my VPN is preventing me from using any docker exposed ports. Sorry for the noise and thank you.

**Comment by fmvilas** [comment]
No worries. Happy it's working now for you.
