### ISSUE TITLE
Polymorphism: schemas with oneOf / allOf not rendering on right side of the Playground 

### ISSUE THREAD

**Issue by CumminsMikeMattern** [asyncapi/playground#36]
v2.0.0
A couple of months ago, i wrote a YAML with polymorphism and it rendered with the "twistees" showing the various options.
Now the same YAML file just shows a blank when I try to "drill down"

**Comment by derberg** [comment]
@CumminsMikeMattern what do you mean by `twistees`? Would be great if you could share some screenshot or something.

The playground underneath uses the html-template. You could try installing AsyncAPI Generator (npm i -g @asyncapi/generator) and then use [the version](https://github.com/asyncapi/html-template/releases) of the template that is a few months old.

**Comment by CumminsMikeMattern** [comment]
Sorry --
The attached snippet of YAML produces the rendering attached 
I highlighted the area that I expected to see oneOf with the 3 schemas:
            - $ref: '#/components/schemas/csuDefineSimpleOperationObject'
            - $ref: '#/components/schemas/gpsDefineSimpleOperationObject'
            - $ref: '#/components/schemas/discardDefineSimpleOperationObject'

**Comment by derberg** [comment]
`oneOf` functionality in HTML was not modified since at least 7 months...hmm 🤔 

so you mean `oneOf` not on a `Message` object but inside a JSON schema of the message payload.

I managed to replicate the error with the following example 🍾 
```
asyncapi: 2.0.0

info:
  title: Signup service example (internal)
  version: 0.1.0

channels:
  /user/signedup:
    subscribe:
      message:
        oneOf:
          - $ref: '#/components/messages/signup'
          - $ref: '#/components/messages/signupattempt'

components:
  messages:
    signup:
      payload:
        type: object
        properties:
          email:
            type: string
            format: email
    signupattempt:
      payload:
        type: array
        items:
          oneOf:
          - type: object
            properties:
              prop1:
                type: string
          - type: object
            properties:
              prop2:
                type: number
```

the result is exactly the same you got
<img width="342" alt="Screenshot 2020-10-09 at 11 09 35" src="https://user-images.githubusercontent.com/6995927/95565079-f6741a00-0a1f-11eb-9a6c-c8009ef6b505.png">

**Comment by CumminsMikeMattern** [comment]
You are spot-on......
Any ideas for a workaround ?

**Comment by derberg** [comment]
not really, it is just not supported/implemented. I just had a quick look at this part

<img width="392" alt="Screenshot 2020-10-09 at 16 31 12" src="https://user-images.githubusercontent.com/6995927/95595849-f0486280-0a4c-11eb-9bd5-cfa25c300fb3.png">

to fix it I had to modify https://github.com/asyncapi/html-template/blob/master/partials/type.html like this

```
{% macro type(prop) %}
{{prop.json('type')}}
{%- if prop.items() -%}
  &lt;
  {%- if prop.items().json and prop.items().json('type') -%}
    {{- prop.items().json('type') -}}
  {% elif prop.items() | isArray -%}
    {%- for p in prop.items() -%}
      {{- type(p) -}}{% if not loop.last %}, {% endif %}
    {%- endfor -%}
  {% elif prop.items().oneOf() %}oneOf
  {% elif prop.items().allOf() %}allOf
  {% elif prop.items().anyOf() %}anyOf
  {%- else -%}
    Unknown
  {%- endif -%}
  &gt;
{%- endif -%}
{% endmacro %}
```

to get

<img width="357" alt="Screenshot 2020-10-09 at 16 30 19" src="https://user-images.githubusercontent.com/6995927/95596014-21c12e00-0a4d-11eb-87ac-62beccf5be8d.png">

more tricky is how to display schema payload in there. I checked Swagger

<img width="564" alt="Screenshot 2020-10-09 at 16 19 17" src="https://user-images.githubusercontent.com/6995927/95596064-343b6780-0a4d-11eb-8432-4dc75c172f0a.png">

but damn, it is ugly

I guess something like this would be expected (looking at my example)

<img width="700" alt="Screenshot 2020-10-09 at 16 39 34" src="https://user-images.githubusercontent.com/6995927/95596767-17536400-0a4e-11eb-9c17-51756892218d.png">

**Comment by CumminsMikeMattern** [comment]
I finally found the screenshot---
In an email dated April 2, 2020, I sent the following 
![image](https://user-images.githubusercontent.com/72101813/95628646-79ab6500-0a4c-11eb-8d81-eb52fc2c478e.png)
.... so what changed between then and now ?

**Comment by derberg** [comment]
@CumminsMikeMattern hey, great you found it, it allowed me to look for an issue and find where it happened. I fixed it here https://github.com/asyncapi/html-template/pull/97

Please try it out and let me know in the PR if it fixes your issues, works well with my example

to try it, install generator and do:
```
ag your-asyncapi.yml https://github.com/derberg/html-template/#fix-oneof -o output
```

**Comment by CumminsMikeMattern** [comment]
Haha, you have mistaken me for a real coder! lol
I have no clue how to do any of that .....I just wanted the Playground to behave like it used to 
If it fixed your example, I am hopeful that it fixed my problem 
When will your fix show up in the Playground?

**Comment by derberg** [comment]
@CumminsMikeMattern can you share your file so I try it out with my fix

you don't need to be a programmer to check it on your own. You just need a terminal:
```bash
#install generator
npm i -g @asyncapi/generator
#run generator with my version of html template with the fix
#you call this command in the terminal in the directory where your-asyncapi.yml file is located
ag your-asyncapi.yml https://github.com/derberg/html-template/#fix-oneof -o output
```

**Comment by CumminsMikeMattern** [comment]
I got the following ...........

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Something went wrong:
Error: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at toError (C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\promise.js:90:14)
    at C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\promise.js:61:36
    at Git.handler (C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\src\git.js:1316:18)
    at Function.Git.fail (C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\src\git.js:1475:18)
    at fail (C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\src\git.js:1433:20)
    at Object.onError (C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\src\git.js:1312:10)
    at C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\simple-git\src\git.js:1439:24

**Comment by derberg** [comment]
you need to have git installed on your machine too https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#_installing_on_windows

**Comment by CumminsMikeMattern** [comment]
Ok, I installed git...........

> puppeteer@5.3.1 install C:\Users\ct043\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\puppeteer
> node install.js

ERROR: Failed to set up Chromium r800071! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Something went wrong:
Error: puppeteer@5.3.1 install: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
    at EventEmitter.emit (events.js:314:20)
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by derberg** [comment]
try `npm config set puppeteer_skip_chromium_download true -g`

**Comment by CumminsMikeMattern** [comment]
Done !
Your template successfully fixed the problem !
THANK YOU for the fix AND for taking the time to walk a noob through the validation thereof !
![image](https://user-images.githubusercontent.com/72101813/96143620-4431cc00-0ed1-11eb-9198-37fa582eded1.png)

**Comment by derberg** [comment]
@CumminsMikeMattern no worries, pleasure on my side 😄 I'm addicted to people happiness 😆 

Checkout the other issue, where I show how it will look like now, displaying proper prop names
