### ISSUE TITLE
hub.asyncapi.io generated HTML docs do not allow to expand / collapse schema objects

### ISSUE THREAD

**Issue by sandpipersburg** [asyncapi/playground#41]
#### Describe the bug
https://hub.asyncapi.io/ generates HTML docs that do not allow to either expand or collapse schema objects, by clicking on the right arrow UI element. 

#### How to Reproduce
1. Go to https://hub.asyncapi.io/.
2. Insert some AsyncAPI spec into the editor, such as Streetlights API. AsyncAPI spec that has schema object inside schema object is the most demonstrative: https://gist.github.com/sandpipersburg/113c5566a8f3b8976d117a2985ff8d5f. 
3. Try to expand or collapse schema objects in a generated HTML doc on the right side of the window. 

Actual behavior: schema objects are not expandable/collapsable. 

#### Expected behavior
Schema objects are expandable/collapsable.

**Comment by fr3shw3b** [comment]
I've recently found this issue also to be the case in https://playground.asyncapi.io.
More precisely, you can expand and collapse a few times and then it stops working and you have minimise or go to a different tab and then come back to be able expand or collapse schemas.

Would this need a separate issue to be created?

**Comment by derberg** [comment]
@fr3shw3b [this](https://github.com/asyncapi/playground/pull/117) issue introduces a new way of rendering docs using our react component and it will also fix this issue in the playground. Once merged, we will close this issue as in the end hub.asyncapi.io is not maintained and will heavily refactored here https://github.com/asyncapi/studio/
