### ISSUE TITLE
Playground: "Required" tags not rendering for objects within arrays 

### ISSUE THREAD

**Issue by CumminsMikeMattern** [asyncapi/playground#43]
#### Describe the bug
In the playground v2.0.0, "required" tags are not rendering for objects within arrays 

#### How to Reproduce
The following YAML renders as expected --
        registrationInfo:
          description: >-
            Registration info object, containing details of equipment for which
            registration details are to be updated.
          type: object
          required:
            - boxID
            - boxType
            - boxHardwareVer
            - boxSoftwareVer
          properties:
            custRef:
              description: The customer reference name.
              type: string
            boxID:
              description: >-
                The telematics provider's box ID that is associated with this
                equipment.
              type: string
            boxType:
              description: The type of telematics box being registered.
              type: string
            boxHardwareVer:
              description: The hardware version of the Telematics box.
              type: string
            boxSoftwareVer:
              type: object

![image](https://user-images.githubusercontent.com/72101813/97592851-7b2ad600-19d7-11eb-9439-0bbaea20fc76.png)

But within an array, the required tags are missing --

            boxSoftwareVer:
              type: object
              description: >-
                The software version of the Telematics box.  Object consists of a
                required element - Firmware Version (for the overall Telematics
                box) and an optional array of App names and corresponding versions
                (if the Telematics box runs individually versioned software
                modules).
              properties:
                boxFirmwareVer:
                  description: The firmware version of the Telematics box.
                  type: string
                appNameVersion:
                  description: >-
                    An optional array of application names and versions. If this
                    optional array is used, then the appName and appVersion for
                    ALL supported applications must be included.
                  type: array
                  items:
                    description: >-
                      Each object in this array consists of an application name
                      and corresponding version.
                    type: object
                    required:
                      - appName
                      - appVersion
                    properties:
                      appName:
                        description: Application Name.
                        type: string
                      appVersion:
                        description: Application Version.
                        type: string
              required:
                - boxFirmwareVer

![image](https://user-images.githubusercontent.com/72101813/97595270-eaa1c500-19d9-11eb-858e-6c44235d8b69.png)

Looking throughout my YAML file, the array seems to be the culprit though I may have jumped to a conclusion

**Comment by derberg** [comment]
@CumminsMikeMattern hey, just opened a PR with a fix https://github.com/asyncapi/html-template/pull/114

**Comment by CumminsMikeMattern** [comment]
Wow that was fast!
Do you need me to check it?
If so, please feed me the 'ag' command

**Comment by derberg** [comment]
would be awesome if you could help with the review: 
```
ag YOUR-FILE https://github.com/derberg/html-template/#fix-required -o output --force-write
```

**Comment by CumminsMikeMattern** [comment]
Gold Star!
![image](https://user-images.githubusercontent.com/72101813/97609710-5429cf80-19ea-11eb-894c-ce644c8e3431.png)

**Comment by derberg** [comment]
awesome, thanks, let me find someone who can approve my PR, and once we release the template, we will update the playground too, hopefully before the weekend
