### ISSUE TITLE
CSS capitalization and lowercase classes on Properties.pattern do not match casing rules of the regular expression

### ISSUE THREAD

**Issue by joshg2k** [asyncapi/playground#6]
<img width="954" alt="Screen Shot 2019-08-21 at 16 21 19" src="https://user-images.githubusercontent.com/4231004/63469400-b9ba1d80-c42f-11e9-9c71-88e9cdddacf6.png">

Here you can see that the pattern requires the string "readMessages" whereas the preview displays "Must Match ReadMessages" which could lead to confusion.

**Comment by fmvilas** [comment]
This was fixed here: https://github.com/asyncapi/generator/pull/87. Thanks!
