### ISSUE TITLE
Not able to use locally

### ISSUE THREAD

**Issue by ma-schmidt-de** [asyncapi/playground#80]
Hi everyone,

I'm aiming to use the AsyncAPI Playground locally and hence followed the [README's section on that](https://github.com/asyncapi/playground#using-it-locally). Unfortunately, I'm running into an error that prevents the html rendering. 

### Steps to reproduce

1. Clone git repo
2. Run `npm install`
3. Run `npm start`
4. Open http://localhost:5000/ and add [Account Service yaml](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml) on the left hand side.

### Results

- No HTML rendered on the right hand side.
- Terminal shows the following:
```==================
POST /html/generate
==================
asyncapi: 2.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
==================
(node:2890) UnhandledPromiseRejectionWarning: TypeError: must call as: npm.load(callback)
    at Object.load (/usr/local/lib/node_modules/npm/lib/npm.js:130:13)
    at npmi (/Users/mschmidt/tools/asyncapi/playground/node_modules/npmi/npmi.js:189:9)
    at /Users/mschmidt/tools/asyncapi/playground/node_modules/@asyncapi/generator/lib/generator.js:377:7
(node:2890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### Context
I'm using `node v14.15.5` and `npm v7.5.3`.

Any chance to work around / fix this?

Cheers,
Matthias

**Comment by derberg** [comment]
@ma-schmidt-de it is not much of a problem with the playground but the generator. Generator at the moment doesn't like npm 7 😞 

Have a look at this thread https://github.com/asyncapi/generator/issues/505

**Comment by ma-schmidt-de** [comment]
Hi @derberg 
Thanks a lot for the instant reply. Downgrading npm to version 6.13.7 did the trick for me. 👍
