### ISSUE TITLE
bearerFormat value in securitySchemes has last character trimmed off unless it is followed by a newline.

### ISSUE THREAD

**Issue by joshg2k** [asyncapi/playground#9]
<img width="722" alt="Screen Shot 2019-08-21 at 15 03 56" src="https://user-images.githubusercontent.com/4231004/63464835-ac983100-c425-11e9-8e61-794d119d9f9d.png">

For example:

      JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt(EOF)

...results in "jw" being displayed in preview panel, whereas...

      JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
      (EOF)

...results in "jwt" being displayed.

The value itself ("jwt" above) does not appear to make a difference.

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #7](https://github.com/asyncapi/html-template/issues/7) via [**ZenHub**](https://www.zenhub.com/)
